version: '3'

services:
  backend:
    build: ./
    container_name: nestjs-instance
    environment:
      - DB_URI='mongodb+srv://mahesh7702017554:WbpRL2rQuyeLK2GB@maheshdev.som5s41.mongodb.net/?retryWrites=true&w=majority&appName=maheshDev'
      - WT_SECTER=secret_key
    ports:
      - '8000:8000'
    depends_on:
      - database
    database:
      image: mongo
      ports:
      - '27017:27017'
      volumes:
      - ./data:/data/db

networks:
